name: "Bug report"
description: "Something seems to be broken…"
labels: ["bug (unverified)"]
assignees: []

body:
  - type: input
    id: version
    attributes:
      label: "Version of Awkward Array"
      description: |
        ```python
        >>> import awkward as ak
        >>> ak.__version__
        ```

        (Your issue might have already been fixed; see [latest version](https://pypi.org/project/awkward/).)
      placeholder: "XX.YY.ZZ"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description and code to reproduce"
      description: |
        - What did you attempt to do? Include code so that we can reproduce it (in [backticks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)).
        - What did you expect it to do?
        - What did it do instead? (Include full log output in [backticks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks). Copy-pasted text is better than screenshots.)

        If your code example requires data, be sure to include it in a way that is publicly accessible, such as **clicking on the rectangle below to highlight it** and then dragging the file in. (You can [pickle](https://docs.python.org/3/library/pickle.html) Awkward Arrays, but verify that the issue applies to pickled arrays as well as the original arrays.)
      placeholder: "Tell us what's not working."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for submitting an issue; we know that it takes time and effort to do so!

        Note that we'll be closing the issue as soon as a solution is proposed. This is not meant to be unfriendly; it's for our own bookkeeping. If you think the first answer/solution is unsatisfactory, please do continue the thread and we'll reopen it or otherwise address it.
