name: Feature request
description: Some functionality needs to be added…
title: Feature Request
labels:
  - feature
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        What you're looking for might already be possible as a combination of existing functions, so these requests might get converted into requests for documentation (with a corresponding change in title).

        Here are some links to documentation, to help you in your search.

           * [The tutorials site](https://awkward-array.org/)
           * [The C++ API](https://awkward-array.readthedocs.io/en/latest/_static/index.html)
           * [The Python API](https://awkward-array.readthedocs.io/en/latest/index.html)
           * [StackOverflow: [awkward-array] tag](https://stackoverflow.com/questions/tagged/awkward-array)
           * [Gitter: Scikit-HEP/awkward-array room](https://gitter.im/Scikit-HEP/awkward-array)
  - type: textarea
    id: feature
    attributes:
      label: Description of New Feature
      description: Please describe the feature that you would like to see implemented.
      placeholder: Tell us what you need!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
